package fr.sazaju.genshin.item;

import static fr.sazaju.genshin.Rarity.*;

import fr.sazaju.genshin.Rarity;

public enum Food implements ItemType.WithSingleRarity {
	/***********/
	/* NATURAL */
	/***********/
	APPLE(ONE_STAR), //
	SUNSETTIA(ONE_STAR), //
	/**********/
	/* COOKED */
	/**********/
	PILE_EM_UP_(THREE_STARS), //
	ADEPTUS_TEMPTATION(FIVE_STARS), //
	ADVENTURER_S_BREAKFAST_SANDWICH(THREE_STARS), //
	ALMOND_TOFU(TWO_STARS), //
	APPLE_CIDER(TWO_STARS), //
	BAMBOO_SHOOT_SOUP(THREE_STARS), //
	BARBATOS_RATATOUILLE(THREE_STARS), //
	BERRY_MINT_BURST(TWO_STARS), //
	BLACK_BACK_PERCH_STEW(THREE_STARS), //
	CALLA_LILY_SEAFOOD_SOUP(THREE_STARS), //
	CHICKEN_MUSHROOM_SKEWER(ONE_STAR), //
	COLD_CUT_PLATTER(THREE_STARS), //
	COME_AND_GET_IT(THREE_STARS), //
	CRAB_ROE_TOFU(TWO_STARS), //
	CRAB_HAM_VEGGIE_BAKE(THREE_STARS), //
	CREAM_STEW(TWO_STARS), //
	CRISPY_POTATO_SHRIMP_PLATTER(THREE_STARS), //
	CRYSTAL_SHRIMP(TWO_STARS), //
	CURED_PORK_DRY_HOTPOT(THREE_STARS), //
	FISHERMAN_S_TOAST(TWO_STARS), //
	FLAMING_RED_BOLOGNESE(TWO_STARS), //
	FRAGRANT_MASHED_POTATOES(THREE_STARS), //
	FRIED_RADISH_BALLS(TWO_STARS), //
	FULLMOON_EGG(THREE_STARS), //
	GOLDEN_CHICKEN_BURGER(THREE_STARS), //
	GOLDEN_CRAB(FOUR_STARS), //
	GOLDEN_FRIED_CHICKEN(FOUR_STARS), //
	GOLDEN_SHRIMP_BALLS(THREE_STARS), //
	GOULASH(TWO_STARS), //
	GRILLED_TIGER_FISH(ONE_STAR), //
	HOLY_WATER(THREE_STARS), //
	JADE_PARCELS(FOUR_STARS), //
	JEWELRY_SOUP(TWO_STARS), //
	JUEYUN_CHILI_CHICKEN(TWO_STARS), //
	JUEYUN_GUOBA(THREE_STARS), //
	LOTUS_FLOWER_CRISP(THREE_STARS), //
	LOTUS_SEED_AND_BIRD_EGG_SOUP(TWO_STARS), //
	MATSUTAKE_MEAT_ROLLS(TWO_STARS), //
	MINT_JELLY(ONE_STAR), //
	MINT_SALAD(TWO_STARS), //
	MINTY_MEAT_ROLLS(THREE_STARS), //
	MONDSTADT_GRILLED_FISH(ONE_STAR), //
	MONDSTADT_HASH_BROWN(THREE_STARS), //
	MOON_PIE(FOUR_STARS), //
	MORA_MEAT(ONE_STAR), //
	MUSHROOM_PIZZA(THREE_STARS), //
	NOODLES_WITH_MOUNTAIN_DELICACIES(TWO_STARS), //
	NORTHERN_APPLE_STEW(THREE_STARS), //
	NORTHERN_SMOKED_CHICKEN(TWO_STARS), //
	POP_S_TEAS(ONE_STAR), //
	QINGCE_STIR_FRY(THREE_STARS), //
	RADISH_VEGGIE_SOUP(ONE_STAR), //
	SATISFYING_SALAD(TWO_STARS), //
	SAUTÉED_MATSUTAKE(THREE_STARS), //
	SQUIRREL_FISH(THREE_STARS), //
	STEAK(ONE_STAR), //
	STICKY_HONEY_ROAST(THREE_STARS), //
	STIR_FRIED_FILET(ONE_STAR), //
	STIR_FRIED_FISH_NOODLES(TWO_STARS), //
	STONE_HARBOR_DELICACIES(TWO_STARS), //
	SUNSHINE_SPRAT(THREE_STARS), //
	SWEET_MADAME(TWO_STARS), //
	TEA_BREAK_PANCAKE(TWO_STARS), //
	TEYVAT_FRIED_EGG(ONE_STAR), //
	TIANSHU_MEAT(FOUR_STARS), //
	TRIPLE_LAYERED_CONSOMMÉ(THREE_STARS), //
	UNIVERSAL_PEACE(THREE_STARS), //
	VEGETARIAN_ABALONE(TWO_STARS), //
	WOLFHOOK_JUICE(TWO_STARS), //
	ZHONGYUAN_CHOP_SUEY(THREE_STARS), //
	;

	private final Rarity rarity;

	private Food(Rarity rarity) {
		this.rarity = rarity;
	}

	@Override
	public Rarity getRarity() {
		return rarity;
	}

	@Override
	public StackableItem<Food> item() {
		return new StackableItem<Food>(this, getRarity());
	}
}
